<?php

namespace common\models\products;

use common\components\LoadTranslates;
use common\models\pack\PdPackagingI18n;
use common\models\products\ProductsI18n;
use common\components\ValidateTrait;
use common\components\LocaleTrait;
//use common\models\emailsProvince\EmailsProvince;
//use common\models\regions\Regions;
//use lhs\Yii2SaveRelationsBehavior\SaveRelationsBehavior;
use Yii;

/**
 * This is the model class for table "products".
 */
class Products extends \yii\db\ActiveRecord
{
    use LoadTranslates;
    use ValidateTrait;

    //public $emails;

//    public static function create($productId)
//    {
//        $model = new static();
//        $model->id = $productId;
//        return $model;
//    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'products';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'order'], 'string'],
            [['i18n'], 'safe'],
            [['i18n'], 'validateLanguageRequire'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'order' => Yii::t('app', 'Product Order'),
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        ProductsI18n::saveLanguageData($this->id, $this->i18n, $insert);

        parent::afterSave($insert, $changedAttributes);
    }


//    /**
//     * @return \yii\db\ActiveQuery
//     */
//    public function getRegions()
//    {
//        return $this->hasMany(Regions::class, ['region_id' => 'id']);
//    }

    /**
     * @return $this
     */
    public function getTransUa()
    {
        return $this->hasOne(ProductsI18n::class, ['product_id' => 'id'])->andWhere([
            'products_i18n.locale' => 'uk'
        ]);
    }
//
//    public function beforeDelete()
//    {
//        if (parent::beforeDelete()) {
//            EmailsProvince::deleteAll(['province_id' => $this->id]);
//            return true;
//        }
//        return false; // TODO: Change the autogenerated stub
//    }

    public function getTranslation()
    {
        return $this->hasMany(ProductsI18n::class, ['product_id' => 'id']);
    }

    public function afterFind()
    {
        self::loadTranslate($this);
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public function getLocale()
    {
        return $this->hasOne(ProductsI18n::class, ['product_id' => 'id'])->andWhere([
            'products_i18n.locale' => Yii::$app->language
        ]);

    }
}
